### ISSUE TITLE
chore: release packaging

### ISSUE THREAD

**Issue by mfw78** [windingtree/videre#7]
Configure automatic github actions release packaging collecting:

- [x] typechain generated for `videre` contracts.
- [x] typescript generated for `protobuf`.
- [x] eip712 signing utilties
